[
[{'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'Italian', 'SeoName': 'italian'}],
 [{'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'Italian', 'SeoName': 'italian'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Café', 'SeoName': 'cafe'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Drinks', 'SeoName': 'drinks'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Italian', 'SeoName': 'italian'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Fish & Chips', 'SeoName': 'fish-and-chips'},
  {'Name': 'British', 'SeoName': 'british'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Brunch', 'SeoName': 'brunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Italian', 'SeoName': 'italian'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Kebab', 'SeoName': 'kebabs'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Peri Peri', 'SeoName': 'peri-peri'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Greek', 'SeoName': 'greek'},
  {'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Supermarkets', 'SeoName': 'supermarkets'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Brunch', 'SeoName': 'brunch'},
  {'Name': 'Brazilian food', 'SeoName': 'brazilian-food'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Middle Eastern', 'SeoName': 'middle-eastern'},
  {'Name': 'Kebab', 'SeoName': 'kebabs'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Caribbean', 'SeoName': 'caribbean'},
  {'Name': 'Vegetarian', 'SeoName': 'vegetarian'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Kebab', 'SeoName': 'kebabs'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'Chicken', 'SeoName': 'chicken'}],
 [{'Name': 'Kebab', 'SeoName': 'kebabs'},
  {'Name': 'Turkish', 'SeoName': 'turkish'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Kebab', 'SeoName': 'kebabs'},
  {'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Healthy', 'SeoName': 'healthy'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Japanese', 'SeoName': 'japanese'},
  {'Name': 'Sushi', 'SeoName': 'sushi'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Indian', 'SeoName': 'indian'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Doughnuts', 'SeoName': 'doughnuts'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'Grill', 'SeoName': 'grill'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Turkish', 'SeoName': 'turkish'},
  {'Name': 'Kebab', 'SeoName': 'kebabs'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Kebab', 'SeoName': 'kebabs'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Turkish', 'SeoName': 'turkish'},
  {'Name': 'Grill', 'SeoName': 'grill'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Italian', 'SeoName': 'italian'},
  {'Name': 'Pasta', 'SeoName': 'pasta'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Italian', 'SeoName': 'italian'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Indian', 'SeoName': 'indian'},
  {'Name': 'Curry', 'SeoName': 'curry'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Burritos', 'SeoName': 'burritos'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Iranian', 'SeoName': 'iranian'},
  {'Name': 'Persian', 'SeoName': 'persian'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Italian', 'SeoName': 'italian'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Healthy', 'SeoName': 'healthy'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Middle Eastern', 'SeoName': 'middle-eastern'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Grill', 'SeoName': 'grill'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Salads', 'SeoName': 'salads'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Bakery', 'SeoName': 'bakery'},
  {'Name': 'Café', 'SeoName': 'cafe'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'British', 'SeoName': 'british'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Gourmet', 'SeoName': 'gourmet'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Grill', 'SeoName': 'grill'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Healthy', 'SeoName': 'healthy'},
  {'Name': 'Smoothies', 'SeoName': 'smoothies'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'Italian', 'SeoName': 'italian'}],
 [{'Name': 'Bagels', 'SeoName': 'bagels'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Brunch', 'SeoName': 'brunch'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Smoothies', 'SeoName': 'smoothies'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Bakery', 'SeoName': 'bakery'},
  {'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Drinks', 'SeoName': 'drinks'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Bakery', 'SeoName': 'bakery'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Crepes', 'SeoName': 'crepes'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Turkish', 'SeoName': 'turkish'},
  {'Name': 'Kebab', 'SeoName': 'kebabs'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Bagels', 'SeoName': 'bagels'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Café', 'SeoName': 'cafe'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Korean', 'SeoName': 'korean'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Vegan', 'SeoName': 'vegan'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Drinks', 'SeoName': 'drinks'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Healthy', 'SeoName': 'healthy'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Tapas', 'SeoName': 'tapas'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Desserts', 'SeoName': 'desserts'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Drinks', 'SeoName': 'drinks'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Café', 'SeoName': 'cafe'},
  {'Name': 'Bakery', 'SeoName': 'bakery'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Ukrainian', 'SeoName': 'ukrainian'},
  {'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Vegan', 'SeoName': 'vegan'},
  {'Name': 'Vegetarian', 'SeoName': 'vegetarian'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Drinks', 'SeoName': 'drinks'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Middle Eastern', 'SeoName': 'middle-eastern'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Portuguese', 'SeoName': 'portuguese'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Café', 'SeoName': 'cafe'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Middle Eastern', 'SeoName': 'middle-eastern'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Drinks', 'SeoName': 'drinks'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Bakery', 'SeoName': 'bakery'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Wraps', 'SeoName': 'wraps'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Bakery', 'SeoName': 'bakery'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Middle Eastern', 'SeoName': 'middle-eastern'},
  {'Name': 'Smoothies', 'SeoName': 'smoothies'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Asian', 'SeoName': 'asian'},
  {'Name': 'Brunch', 'SeoName': 'brunch'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Seafood', 'SeoName': 'seafood'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Halal', 'SeoName': 'halal'}],
 [{'Name': 'Thai', 'SeoName': 'thai'},
  {'Name': 'Malaysian', 'SeoName': 'malaysian'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'Italian', 'SeoName': 'italian'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Middle Eastern', 'SeoName': 'middle-eastern'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Kebab', 'SeoName': 'kebabs'},
  {'Name': 'Burgers', 'SeoName': 'burgers'}],
 [{'Name': 'Vietnamese', 'SeoName': 'vietnamese'},
  {'Name': 'Baguettes', 'SeoName': 'baguettes'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Wraps', 'SeoName': 'wraps'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Baguettes', 'SeoName': 'baguettes'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Greek', 'SeoName': 'greek'},
  {'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Crepes', 'SeoName': 'crepes'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Milkshakes', 'SeoName': 'milkshakes'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Bagels', 'SeoName': 'bagels'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Drinks', 'SeoName': 'drinks'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Persian', 'SeoName': 'persian'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Middle Eastern', 'SeoName': 'middle-eastern'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Cakes', 'SeoName': 'cakes'}],
 [{'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'Pasta', 'SeoName': 'pasta'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Bagels', 'SeoName': 'bagels'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Café', 'SeoName': 'cafe'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'British', 'SeoName': 'british'},
  {'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Vegan', 'SeoName': 'vegan'},
  {'Name': 'Vegetarian', 'SeoName': 'vegetarian'},
  {'Name': 'Halal', 'SeoName': 'halal'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'British', 'SeoName': 'british'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Indian', 'SeoName': 'indian'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Drinks', 'SeoName': 'drinks'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Brazilian food', 'SeoName': 'brazilian-food'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Italian', 'SeoName': 'italian'},
  {'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Arabic', 'SeoName': 'arabic'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lebanese', 'SeoName': 'lebanese'},
  {'Name': 'Kebab', 'SeoName': 'kebabs'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Greek', 'SeoName': 'greek'},
  {'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Drinks', 'SeoName': 'drinks'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Smoothies', 'SeoName': 'smoothies'},
  {'Name': 'Healthy', 'SeoName': 'healthy'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Vegetarian', 'SeoName': 'vegetarian'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Mediterranean', 'SeoName': 'mediterranean'},
  {'Name': 'Grill', 'SeoName': 'grill'},
  {'Name': 'Halal', 'SeoName': 'halal'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Café', 'SeoName': 'cafe'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Mexican', 'SeoName': 'mexican'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Ice Cream', 'SeoName': 'icecream'},
  {'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Smoothies', 'SeoName': 'smoothies'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Italian', 'SeoName': 'italian'},
  {'Name': 'British', 'SeoName': 'british'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Café', 'SeoName': 'cafe'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Italian', 'SeoName': 'italian'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Doughnuts', 'SeoName': 'doughnuts'},
  {'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Brunch', 'SeoName': 'brunch'},
  {'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Café', 'SeoName': 'cafe'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Kebab', 'SeoName': 'kebabs'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Halal', 'SeoName': 'halal'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Healthy', 'SeoName': 'healthy'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Healthy', 'SeoName': 'healthy'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Chicken', 'SeoName': 'chicken'},
  {'Name': 'Healthy', 'SeoName': 'healthy'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Groceries', 'SeoName': 'groceries'},
  {'Name': 'Alcohol', 'SeoName': 'alcohol'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Doughnuts', 'SeoName': 'doughnuts'},
  {'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Pizza', 'SeoName': 'pizza'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Desserts', 'SeoName': 'desserts'},
  {'Name': 'American', 'SeoName': 'american'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Healthy', 'SeoName': 'healthy'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Lunch', 'SeoName': 'lunch'},
  {'Name': 'Healthy', 'SeoName': 'healthy'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Coffee', 'SeoName': 'coffee'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Healthy', 'SeoName': 'healthy'},
  {'Name': 'Smoothies', 'SeoName': 'smoothies'},
  {'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Bagels', 'SeoName': 'bagels'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Bagels', 'SeoName': 'bagels'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Bagels', 'SeoName': 'bagels'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Bakery', 'SeoName': 'bakery'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Bakery', 'SeoName': 'bakery'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Bakery', 'SeoName': 'bakery'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Breakfast', 'SeoName': 'breakfast'},
  {'Name': 'Bakery', 'SeoName': 'bakery'},
  {'Name': 'Sandwiches', 'SeoName': 'sandwiches'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Tapas', 'SeoName': 'tapas'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 [{'Name': 'Burgers', 'SeoName': 'burgers'},
  {'Name': 'Tapas', 'SeoName': 'tapas'},
  {'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}],
 

[

{'Name': 'Desserts', 'SeoName': 'desserts'},

{'Name': 'Portuguese', 'SeoName': 'portuguese'},

{'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}

]

 
 ,
 
 
 
[
     
{'Name': 'Desserts', 'SeoName': 'desserts'},

{'Name': 'Portuguese', 'SeoName': 'portuguese'},

{'Name': 'Low Delivery Fee', 'SeoName': 'low-delivery-fee'}
  
]
 
 
 
 
 ]